### ISSUE TITLE
No compila

### ISSUE THREAD

**Issue by kunio83** [ErnestoNCarrea/lazaro#1]
Hola, soy Marcos de Buenos Aires, quería avisar que faltan incluir en el git unas clases dentro de Lfx.Backups. Las podrías incluir? capaz que así logro hacer que compile.
Muchas gracias!

**Comment by ErnestoNCarrea** [comment]
Hola Marcos, creo que ya están todos los archivos que faltaban. ¿Me podés confirmar? Saludos.

**Comment by kunio83** [comment]
Hola, si si quedo todo joya. Muchas gracias!
