### ISSUE TITLE
Boton guardar en recibo de pago imprime

### ISSUE THREAD

**Issue by nico9julio** [ErnestoNCarrea/lazaro#12]
Creando un recibo de pago nuevo, al presionar el boton Guardar el comprobante se imprime.
Al lado del botón Guardar hay otro que dice Imprimir, por lo tanto, el comportamiento correcto debería ser asentar el comprobante sin enviar la impresión.
El problema es que no hay manera de asentar un pago sin imprimir el comprobante. Muchas veces esto no es necesario (ajustes de cuenta o diferencias de centavos).

**Comment by ErnestoNCarrea** [comment]
Hola nico9julio. Disculpá la demora en la respuesta.

El problema que mencionás es en realidad una característica configurable en Lázaro. A diferencia de otros comprobantes, los recibos no pueden dejarse guardados sin asentar movimientos. Es por esta razón que los mismos se imprimen automáticamente.

Para cambiar el comportamiento predeterminado, es necesario editar el tipo de comprobante "Recibo de cobro" o "Recibo de pago" o ambos y cambiar la opción de impresión automática. Para esto:
- Usar la opción de menú Comprobantes -> Tablas -> Tipos de comprobante.
- Seleccionar el tipo de comprobante (por ejemplo Recibo de cobro).
- Cambiar la opción "Imprimir automáticamente al guardar" de "Sí" a "No".
- Guardar los cambios.
- Salir de Lázaro y volver a ingresar.

Es necesario ser muy cuidadoso al editar el tipo de comprobante y no cambiar otras opciones que pueden tener efectos inesperados.

Espero que te ayude.

Saludos.

**Comment by nico9julio** [comment]
Disculpame que dupliqué el ticket, no recordaba haber publicado... jaja.
Comprendido, Saludos!
