### ISSUE TITLE
Impresión inválida Hasar 441f

### ISSUE THREAD

**Issue by sebasmoyano** [ErnestoNCarrea/lazaro#2]
Estoy tratando de imprimir una factura A con una impresora Hasar modelo smh/441f y obtengo datos incorrectos en la impresión final.

![lazaro_error](https://cloud.githubusercontent.com/assets/5084534/18033930/22c133ba-6d06-11e6-8a5e-192d092f08ba.jpeg)

Como se puede visualzar en la imagen los campos IVA y Cambio son incorrectos.

**Comment by ErnestoNCarrea** [comment]
Hola Sebastián. Gracias por tu reporte de error.

Te hago un pregunta: ¿esto estaba funcionando bien y ahora comenzó a funcionar mal o es la primera vez que lo usás?

Además, veo que clonaste el repo y tenés modificaciones. Si querés aportar bugfixes o mejoras podés hacer un pull request y lo incorporamos al master.

**Comment by sebasmoyano** [comment]
Es la primera vez que lo usamos. Tanto producto y cliente fueron cargados con la configuración adecuada. Estamos probando con la versión disponible para descargar en la web. 

Sí se emiten comprobantes tipo B funciona bien.

**Comment by ErnestoNCarrea** [comment]
Acabo de publicar una modificación que espero que solucione el problema. Está en el canal beta. Para acceder al canal beta, tenés que cambiar en las preferencias donde dice "Recibir actualizaciones" y seleccionar "En prueba".
Por favor probalo una vez actualizado y decime si emite correctamente los comprobantes A y B.

**Comment by sebasmoyano** [comment]
Muchas gracias por tu feedback! Estamos más cerca, parece que está multiplicando por un ℅ incorrecto:

![img-20160828-wa0002](https://cloud.githubusercontent.com/assets/5084534/18039874/49cd8ee4-6da7-11e6-995a-72f3fc3e8045.jpg)

**Comment by ErnestoNCarrea** [comment]
Estaba enviando el importe IVA (2.1) y no el porcentaje de IVA (21). Creo que ahora va funcionar bien, te va a llegar una actualización.

Por favor probalo con un importe que no sea redondo, por ejemplo con $ 8 o $ 20.

Si funciona OK, podés volver al canal de actualizaciones estables (la aplicación no se va a desactualizar).

**Comment by sebasmoyano** [comment]
Funcionó bien! Muchísimas gracias Ernesto.

**Comment by sebasmoyano** [comment]
Podés crear un branch por favor con el fix? o ponerlo en el master? Es para actualizar mi repositorio.

**Comment by ErnestoNCarrea** [comment]
Ya está comiteado en master.

**Comment by sebasmoyano** [comment]
Gracias!
