### ISSUE TITLE
Carga de productos con IVA

### ISSUE THREAD

**Issue by sebasmoyano** [ErnestoNCarrea/lazaro#3]
Habitualmente se tienenlos precios con IVA. Para que al momento de cargar artículos no haya que estar haciendo cálculos, se podría tener un nuevo campo en los artículos que permita cargar el precio con IVA. Es decir, cargar indistintamente precio con IVA o sin IVA, y que un campo se calcule en base a otro.

Esto creo que Tango Gestión lo maneja así.

**Comment by ErnestoNCarrea** [comment]
Implementado en la última actualización
