### ISSUE TITLE
Error al compilar proyecto

### ISSUE THREAD

**Issue by ghost** [ErnestoNCarrea/lazaro#5]
Al hacer el build no encuentra el espacio de nombres "Base".
Lazaro.Base.Util.Impresion.Comprobantes.Fiscal.EstadoServidorFiscal

Podés verificar?

**Comment by ErnestoNCarrea** [comment]
La solución estaba desactualizada. Algunos proyectos estaban publicados pero no estaban incluidos en la solución.

Ya está arreglado. Por favor probalo.
